name: ci
on:
  push:
    branches:
      - '*'
  pull_request:

env:
  GO_VERSION: 1.19

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
